# --------------------------------------------------------------------------------------------------
# Draft for production docker-compose runtime. Extends the development docker-compose file
# (see https://docs.docker.com/compose/extends/).
# --------------------------------------------------------------------------------------------------

services:
  # ---------------------- NGINX ---------------------- #
  nginx:
    container_name: "ethicapp-nginx"
    build:
      context: web-nginx
      args:
        NGINX_VERSION: 1.23.3
        NODE_PORT: ${NODE_PORT}
    restart: "unless-stopped"
    networks:
      default:
    ports:
      - "${NGINX_WEBAPP_PORT}:80"
    depends_on:
      - node

  # Ensuring no additional ports are exposed.
  #* Update: that won't work, see https://github.com/docker/compose/issues/3729
  node:
    ports: []

  postgres:
    ports: []
