version: "3.8"

services:
  # NGINX
  nginx:
    container_name: "nginx-container"
    build:
      context: web-nginx
      args:
        - NGINX_VERSION=1.22
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - default

  # Web app
  node:
    container_name: "ethicapp"
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION}
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    volumes:
      - .:/home/app
    ports:
      - "${WEB_APP_PORT}:8501"
    networks:
      - default

  # Database
  postgres:
    container_name: "postgres-ethicapp"
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: app2020
      POSTGRES_DB: postgres
    networks:
      - default

  # PGAdmin for local debugging and monitoring
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "${PG_ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

networks:
  default:
