version: "3.9"

networks:
  default:

services:
  # ---------------------- Node web app ---------------------- #
  node:
    container_name: "ethicapp-node"
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "${WEB_APP_PORT}:8501"
    volumes:
      - ".:/home/app:rw"
    depends_on:
      - postgres

  # ---------------------- Database ---------------------- #
  postgres:
    container_name: "ethicapp-postgres"
    build:
      context: postgres-db/
      args:
        UBUNTU_VERSION: "22.04"
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_LOG_LEVEL: 1
      PGPORT: 5432
      PGDATA: /var/lib/postgresql/${POSTGRES_VERSION}/main
    restart: "unless-stopped"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "su healthcheckuser -c pg_isready"]
      interval: 20s
      timeout: 5s
      retries: 1
      start_period: 10s
    volumes:
      - "./db-data-volume:/var/lib/postgresql/${POSTGRES_VERSION}/main:rw"

  # ---------------------- PGAdmin ---------------------- #
  pgadmin:
    container_name: "ethicapp-pgadmin"
    build:
      context: pgadmin/
      args:
        PGADMIN_VERSION: 6.14
        POSTGRES_CONN_PORT: 5432
        POSTGRES_CONN_USER: app
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - default
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
