version: "3.9"

networks:
  default:

services:
  # ---------------------- NGINX ---------------------- #
  # nginx:
  #   container_name: "ethicapp-nginx"
  #   build:
  #     context: web-nginx
  #     args:
  #       NGINX_VERSION: 1.22
  #       WEB_APP_PORT: ${WEB_APP_PORT}
  #   networks:
  #     - default
  #   restart: unless-stopped
  #   ports:
  #     - "${NGINX_LISTEN_PORT}:80"
    # depends_on:
    #   - node

  # ---------------------- Node web app ---------------------- #
  node:
    container_name: "ethicapp-node"
    build:
      context: .
      args:
        NODE_VERSION: "12.22.9-buster"
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
    ports:
      - "${WEB_APP_PORT}:8501"
    networks:
      - default
    volumes:
      - ".:/home/app:rw"
    depends_on:
      - postgres

  # ---------------------- Database ---------------------- #
  # postgres:
  #   container_name: "ethicapp-postgres"
  #   image: "postgres:10.19-bullseye"
  #   volumes:
  #     - ./postgres-volume:/var/lib/postgresql/10/main:rw
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: app2020
  #     POSTGRES_DB: postgres
  #   networks:
  #     - default
  postgres:
    container_name: "ethicapp-postgres"
    build:
      context: postgres-db
      args:
        UBUNTU_VERSION: "22.04"
        POSTGRES_VERSION_MAJOR: ${POSTGRES_VERSION_MAJOR}
    environment:
      POSTGRES_VERSION_MAJOR: ${POSTGRES_VERSION_MAJOR}
      POSTGRES_LOG_LEVEL: 1
      PGPORT: 5432
      PGDATA: /var/lib/postgresql/${POSTGRES_VERSION_MAJOR}/main
    restart: "no" #unless-stopped #!
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 5s
      retries: 1
      start_period: 10s
    volumes:
      - ./postgres:/var/lib/postgresql/${POSTGRES_VERSION_MAJOR}/main:rw
      #- ./postgres-db/data-volume:/var/lib/postgresql/${POSTGRES_VERSION_MAJOR}/main:rw

  # ---------------------- PGAdmin ---------------------- #
  pgadmin:
    container_name: "ethicapp-pgadmin"
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - default
    ports:
      - "${PGADMIN_PORT}:80"
