# --------------------------------------------------------------------------------------------------
# DEVELOPMENT docker-compose.
# --------------------------------------------------------------------------------------------------

version: "3.9"

networks:
  ethicapp-network:
    external: true



secrets:
  jwt_token:
    file: ./secrets/jwt_token

services:
  # ---------------------- Node web app ---------------------- #
  node:
    container_name: "ethicapp"
    image: ethicapp/stable-2:latest
    environment:
      NODE_ENV: release
      NODE_PORT: ${NODE_PORT}
    restart: "no"
    networks:
      - ethicapp-network
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    secrets:
      - jwt_token
    volumes:
      - ethicapp:/home/app:rw
        
  # ---------------------- Nginx ---------------------- #
  nginx:
    container_name: "ethicapp-nginx"
    build:
      context: web-nginx/
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      NGINX_PORT: ${NGINX_PORT}
      NODE_PORT: ${NODE_PORT}
      NODE_SERVER: node
    networks:
      - ethicapp-network
    volumes:
      - ethicapp:/usr/share/nginx/:rw
    depends_on:
      - node

volumes:
  ethicapp: