# --------------------------------------------------------------------------------------------------
# DEVELOPMENT docker-compose.
# --------------------------------------------------------------------------------------------------

version: "3.9"

networks:
  default:

services:
  # ---------------------- Node web app ---------------------- #
  node:
    container_name: "ethicapp-node"
    build:
      context: ethicapp/
      dockerfile: imageRenewal.Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    environment:
      NODE_ENV: development
      NODE_PORT: ${NODE_PORT}
    restart: "no"
    networks:
      default:
    ports:
      - "${NODE_PORT}:${NODE_PORT}"