version: "3.9"

networks:
  default:

services:
  # ---------------------- NGINX ---------------------- #
  nginx:
    container_name: "ethicapp-nginx"
    build:
      context: web-nginx
      args:
        NGINX_VERSION: 1.22
        WEB_APP_PORT: ${WEB_APP_PORT}
    ports:
      - "${NGINX_LISTEN_PORT}:80"
    networks:
      - default
    restart: "unless-stopped"
    # depends_on:
    #   - node

  # ---------------------- Node web app ---------------------- #
  node:
    container_name: "ethicapp-node"
    build:
      context: .
      args:
        NODE_VERSION: "12.22.9-buster"
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    volumes:
      - .:/home/app
    ports:
      - "${WEB_APP_PORT}:8501"
    networks:
      - default

  # ---------------------- Database ---------------------- #
  postgres:
    container_name: "ethicapp-postgres"
    image: "postgres:10.19-bullseye"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: app2020
      POSTGRES_DB: postgres
    networks:
      - default

  # ---------------------- PGAdmin ---------------------- #
  pgadmin:
    container_name: "ethicapp-pgadmin"
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "${PG_ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - default
